[package]
name = "dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

hapi-rs = {path = "../hapi-rs"}
once_cell = "*"
#flume = "*"
crossbeam-channel = "0.5.1"
env_logger = "0.9.0"
log = "0.4.14"
