[package]
name = "gui"
version = "0.1.0"
authors = ["alexxbb <hou.alexx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "^0.9"
relm = "^0.20"
relm-derive = "^0.20"

hapi-rs = {path = "../hapi-rs"}
