[package]
name = "hapi-rs"
version = "0.1.0"
authors = ["Alex Rusev <hou.alexx@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4"
paste = "1.0"

[dev-dependencies]
once_cell = "1.5.2"
env_logger = "0.8.2"